<?php

/**
 * Generated by Yohni
 * https://github.com/yohni
 * yohni.123@gmail.com
 **/

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $table = 'article';
    protected $primaryKey = 'id';
    protected $fillable = [
        'name', 'photo', 'type', 'link'
    ];
}