<?php

/**
 * Generated by Yohni
 * https://github.com/yohni
 * yohni.123@gmail.com
 **/

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Courier extends Model
{
    protected  $table = 'couriers';

    protected $fillable = [
        'name', 'cost'
    ];

}