<?php

/**
 * Generated by Yohni
 * https://github.com/yohni
 * yohni.123@gmail.com
 **/

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $table = 'orders';
    protected $primaryKey = 'id';
    protected $fillable = [
        'id_user', 'status', 'id_voucher',
        'sumcost', 'payment',
        'address', 'range', 'ongkir'
    ];
    public function user()
    {
        return $this->belongsTo('App\Models\User', 'id_user');
    }

    public function product()
    {
        return $this->belongsToMany('App\Models\Product')
            ->using('App\Models\OrderProduct')
            ->withPivot([
                'quantity',
                'cost',
            ]);
    }
}