<?php

/**
 * Generated by Yohni
 * https://github.com/yohni
 * yohni.123@gmail.com
 **/

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Order extends Model
{
    use SoftDeletes;
    protected $table = 'orders';
    protected $primaryKey = 'id';
    protected $fillable = [
        'id_user', 'status', 'id_voucher',
        'cost', 'payment', 'id_product',
        'address', 'range', 'ongkir', 'orderr_id'
    ];
    public function user()
    {
        return $this->belongsTo('App\Models\User', 'id_user');
    }

    public function product()
    {
        return $this->belongsTo('App\Models\Product', 'id_product');
    }
}