<?php

/**
 * Generated by Yohni
 * https://github.com/yohni
 * yohni.123@gmail.com
 **/

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Wishlist extends Model
{
    protected $table = 'wishlists';
    protected $primaryKey = 'id';
    protected $fillable = [
        'id_user', 'id_product',
    ];

    public function product()
    {
        return $this->belongsTo('App\Models\Product', 'id_product');
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User', 'id_user');
    }
}